name: campus_bus_management
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  razorpay_flutter: 
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  animated_flip_counter: ^0.3.4
  multi_select_flutter: ^4.1.3
  fl_chart: ^0.70.2
  path: ^1.9.1
  camera: ^0.11.1
  path_provider: ^2.1.5
  google_mlkit_face_detection:
  image:
  logger:
  shared_preferences: ^2.5.3
  url_launcher:
  pdf:
  open_file:
  google_maps_flutter: ^2.12.3
  file_picker: ^10.3.3
  permission_handler: ^12.0.1
  # Location & Maps
  geolocator:
  geocoding:
  flutter_map:
  latlong2:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/  # Your image asset directory should be defined here.
    - assets/fonts/NotoSans-Regular.ttf
  # Additional comments can be added here, as shown below:
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here.
  # Each entry in this list should have a "family" key with the font family name,
  # and a "fonts" key with a list giving the asset and other descriptors for the font.
  # Example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package